### ISSUE TITLE
Call for Speakers: January

### ISSUE THREAD

**Issue by nickdesaulniers** [peninsulajs/peninsulajs.github.io#2]
We're looking for speakers for the first meeting of our new meetup!

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:nick@mozilla.com?Subject=PeninsulaJSJanCFP&CC=potch@mozilla.com).

**When and Where will it be?**
Wednesday January 27th (1/27/16)
Doors open 6pm
Starts at 7pm
Wraps at 9pm

Mozilla Corporation
331 Evelyn Ave
Mountain View, CA 94040
[Map](https://www.bing.com/maps/#Y3A9MzcuMzg4NjAwfi0xMjIuMDYxOTAwJmx2bD00JnN0eT1yJnNzPXlwLllOODczeDk3Nzc2NzcwNzk1NDM4ODM0NjZ+cGcuMX5yYWQuODA=)

**What should I talk about?**
We don’t have a strict formula, but we love all things JavaScript and the Web!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
 Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
 Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a projector and a mic for you to use.

Template stolen w/ :heart:  from [WaffleJS](https://github.com/wafflejs/wafflejs.github.io).

**Comment by tbranyen** [comment]
Would be happy to put together a short talk on Redux and my work on diffHTML. I've recently built a tool for Netflix's global launch using this approach. I think it's rather novel and interesting since every state change effectively re-renders the entire page (in the same sense as React). 10 minutes would be enough time to briefly introduce what Redux and diffHTML are and do a quick sample highlighting why you should check out either project.

**Comment by MylesBorins** [comment]
Oh hey!

How long are the talks to be?

**Comment by nickdesaulniers** [comment]
10 minutes.  Will edit my initial comment.

**Comment by potch** [comment]
@TheAlphaNerd 10 minutes- definitely riffing on the @wafflejs style

**Comment by MylesBorins** [comment]
I'd love to give my 10 minute talk about doing distributed synthesis using a mobile orchestra of phones.

I could also give a 10 minute lay down of how node.js versions work

I could also give a 10 minute git seminar... OMG IT'S A TREE

edit: let me know if you need more details

**Comment by potch** [comment]
@tbranyen sounds great!

**Comment by potch** [comment]
@TheAlphaNerd the mobile phone orchestra is relevant to our interests and we wish to <s>subscribe to your newsletter</s> have you present

**Comment by potch** [comment]
@tbranyen @TheAlphaNerd the first event is free so there's no special comp tickets- can you register at https://ti.to/peninsulajs/jan-16?

**Comment by tbranyen** [comment]
All set @potch

**Comment by MylesBorins** [comment]
@potch will people be able to cowork at mozilla before the event?

**Comment by potch** [comment]
@TheAlphaNerd sure!

**Comment by mapmeld** [comment]
I'd like to do a 10 minute talk on "Crossword Puzzles in Burmese". It's partly about a new JS app that I've made, partly about server-side <canvas>, and partly about making sense of Unicode

**Comment by potch** [comment]
@mapmeld- that sounds fantastic, please do! The first event is free so there's no special comp tickets- can you register at https://ti.to/peninsulajs/jan-16?

**Comment by potch** [comment]
@mapmeld @TheAlphaNerd @tbranyen Can you send me a talk title and either a twitter handle or appropriate canonical URL for yourself?

**Comment by tbranyen** [comment]
@potch

"Redux & diffHTML: Re-rendering your document element"
@tbranyen http://tbranyen.com

**Comment by mapmeld** [comment]
@potch 
"Crossword Puzzles in Burmese" I'm mapmeld on Twitter as well. http://mapmeld.com

**Comment by nickdesaulniers** [comment]
thanks for submissions! All speakers have been notified, CFPs for February should go [here](https://github.com/peninsulajs/peninsulajs.github.io/issues/3).
